# NOTE: Full sensor rendering requires a backbuffer of 1024x6912.
# NOTE 2: First element in list should be the highest FPS camera. 
# Every other camera has a camera with a relative framerate to that camera. 
#

# All sensors for new scenes & trjectories
#camera_list: [left_gray, right_gray, down_gray, left_rgb_blurred, down_rgb_blurred, left_depth, down_depth, left_segmented, down_segmented]

# For testing
#camera_list: [left_gray]
#camera_list: [left_gray, right_gray, down_gray]

# new for IJRR
camera_list: [left_rgb_blurred, down_rgb_blurred, left_segmented, down_segmented, left_depth, down_depth]
#camera_list: [left_rgb_blurred, down_rgb_blurred, left_segmented, down_segmented]

# HEVC compressed IJRR sensors
#camera_list: [left_rgb_blurred, down_rgb_blurred, left_depth, down_depth, left_segmented, down_segmented]

# Raycasted depth sensors
#camera_list: [left_depth, down_depth]

# New environment grayscales.
#camera_list: [left_gray, right_gray, down_gray]


# enum outputShaderType {
#   RGB = -1,
#   InstanceID = 0,
#   SemanticID = 1,
#   DepthCompressed = 2,
#   DepthMultiChannel = 3,
#   SurfaceNormals =4
#   grayscale=5
# }


# Grayscale (120Hz)
left_gray:
    tf: left
    ID: "Camera_Left_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5        

right_gray:
    tf: right
    ID: "Camera_Right_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5        

down_gray:
    tf: down
    ID: "Camera_Down_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5     

# Depth (120Hz/2 = 60Hz)
left_depth:
    tf: left
    ID: "Camera_Left_Depth"                     
    outputShaderType: 3        
    inverseRelativeFramerate: 2

down_depth:
    tf: down
    ID: "Camera_Down_Depth"
    outputShaderType: 3 
    inverseRelativeFramerate: 2

# RGB Blurred (120Hz/2 = 60Hz)
left_rgb_blurred:
    tf: left
    ID: "Camera_Left_RGB"
    motionBlurPercent: 1.0                     
    outputShaderType: -1       
    inverseRelativeFramerate: 2

down_rgb_blurred:
    tf: down
    ID: "Camera_Down_RGB"
    motionBlurPercent: 1.0                     
    outputShaderType: -1      
    inverseRelativeFramerate: 2 

# Segmentation (120Hz/2 = 60Hz)
left_segmented:
    tf: left
    ID: "Camera_Left_Segmented"
    motionBlurPercent: 0.0                     
    outputShaderType: 1    
    inverseRelativeFramerate: 2    

down_segmented:
    tf: down
    ID: "Camera_Down_Segmented"
    motionBlurPercent: 0.0                     
    outputShaderType: 1   
    inverseRelativeFramerate: 2     
